# Generated by Django 4.2.7 on 2024-05-14 23:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2024, 5, 14, 23, 46, 44, 602184, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
    ]
