# Generated by Django 4.2.7 on 2024-05-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0002_generatedimage_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="shared",
            field=models.BooleanField(default=False),
        ),
    ]
