# Generated by Django 4.2.7 on 2024-05-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0003_generatedimage_shared"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="model",
            field=models.CharField(
                default="Ojimi/anime-kawai-diffusion", max_length=255
            ),
        ),
    ]
