# Generated by Django 4.2.7 on 2024-05-21 02:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0006_alter_generatedimage_style"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generatedimage",
            name="created_at",
        ),
    ]
