# Generated by Django 4.2.7 on 2024-05-21 02:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0007_remove_generatedimage_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedimage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
