# Generated by Django 4.2.7 on 2024-05-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_generator", "0008_generatedimage_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generatedimage",
            name="model",
            field=models.CharField(
                default="runwayml/stable-diffusion-v1-5", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="generatedimage",
            name="style",
            field=models.CharField(
                default=",Die-cut sticker,white background, illustration minimalism, vector, pastel colors",
                max_length=255,
            ),
        ),
    ]
