# Generated by Django 5.0.7 on 2024-08-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_generator', '0009_alter_generatedimage_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedimage',
            name='shared',
            field=models.BooleanField(default=True),
        ),
    ]
